# Uncomment this line to define a global platform for your project

target 'My_Swift_Meteo_Server' do
  use_frameworks!

  pod 'Alamofire', '~> 3.4'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'SwiftyBeaver'
  pod 'SwiftMongoDB'
end
